/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface GetCssResult {
  css: string
  error: string
}
export function getCSS(themeData: string, classNamePrefix: string): GetCssResult
export interface HighlightResult {
  html: string
  language: string
}
export function highlight(code: string, language: string, prefix: string): HighlightResult
